### ISSUE TITLE
Enable easy scaling of TikZ picture after generation

### ISSUE THREAD

**Issue by kjellmf** [xyz2tex/svg2tikz#10]
When including a PDF of PNG figure into a document, one typically achieves this with something like

```
\includegraphics[width=0.7\linewidth]{myfig}
```

This way, the same figure can be included into multiple documents and/or have its width adjusted after generation

It would be very useful if the TikZ code was generated to make something like this possible:

```
\newlength\tikzfigwidth
\newcommand{\includetikz}[2][0.9\linewidth]{%
    \setlength\tikzfigwidth{#1}%
    \scriptsize%
    \input{#2}%
} 

\includetikz[0.5\linewidth]{myfig.tikz}
```

I.e., the TikZ figures are generated as multiplies of a \tikzfigwidth length.

Not sure how to implement this. Any ideas?

**Comment by ldevillez** [comment]
Global scale is already in there
