### ISSUE TITLE
Setup section in bug issue template

### ISSUE THREAD

**Issue by samcarter** [xyz2tex/svg2tikz#107]
The current bug issue template reads:

```
**Setup:**
 - Mode: inkscape/python package/shell tool
 - Inkscape version: [e.g 1.1] when using with inkscape
 - Version [e.g. 1.2]
```

- As the current version numbers of inkscape and svg2tikz happen to be quite similar at the moment, maybe it would be clearer to ask for `svg2tikz version [e.g. 1.2]` instead of just `Version [e.g. 1.2]`. 

- From a user point of view, I would also expect the order to be different. First ask for the version number of svg2tikz, as that's the tool I'm reporting a bug about and after that ask for other details, like the inkscape version.

- I don't know how useful knowing the operating system is for you, but maybe include a question about the OS as well? 

- And just a tiny detail: there seems to be a missing in `[e.g_ . _ 1.1] `

**Comment by ldevillez** [comment]
Thanks :)
