### ISSUE TITLE
Error while exporting images via inkscape from the command line

### ISSUE THREAD

**Issue by samcarter** [xyz2tex/svg2tikz#111]
If use inkscape to export to an image (not to tikz, to other formats like png) from the command line, e.g.

```
inkscape --export-type=png  test.pdf
```

I will see the following error message

```
<path to svg2tikz>/tikz_export_effect.inx:3: parser error : Opening and ending tag mismatch: name line 3 and _name
  <name>Export to TikZ path</_name>
                             ^
```

The error goes away when I change https://github.com/xyz2tex/svg2tikz/blob/master/svg2tikz/extensions/tikz_export_effect.inx#L3 from

```
  <name>Export to TikZ path</_name>
```

to

```
  <name>Export to TikZ path</name>
```

----

Furthermore I get the following warning 4 times:

```
** (org.inkscape.Inkscape:60097): WARNING **: 14:48:02.269: Invalid child element ('br') in notebook page in extension 'net.texample.tools.svg.export_tikz.effect'.
```
 
Can I assume this warning is harmless? 

**Setup:**
 - Mode: inkscape (via command line)
 - SVG2TikZ version: 2.0.0
 - OS version: macOS 13.3.1
 - Inkscape version: 1.2

**Comment by ldevillez** [comment]
Fixed !
And thanks for all your feedback, really appreciated !

**Comment by samcarter** [comment]
Your fix works perfectly! Thanks a lot!
