### ISSUE TITLE
The PDF generated by the converted Tikz code is very different from the original SVG image

### ISSUE THREAD

**Issue by saxyx** [xyz2tex/svg2tikz#119]
**Describe the bug**
The PDF generated by the converted Tikz code is very different from the original SVG image

**Setup:**
 - Mode: inkscape
 - SVG2TikZ version: v2.0.0 
 - OS version: Windows 10
 - Inkscape version: 1.2.1

[3.svg](https://github.com/xyz2tex/svg2tikz/assets/50071422/4de2e67b-13ed-48f2-aa73-0e9c6dab96b9)
[3.pdf](https://github.com/xyz2tex/svg2tikz/files/11545654/3.pdf)

**Comment by ldevillez** [comment]
Thanks @saxyx, I will look into it when I have time :)

**Comment by saxyx** [comment]
Thanks a lot!
This svg file is generated by dynamic mathematics software GeoGebra, and I don't know much about the xml language used in svg.
I found that instead of ungroup all elements, I could just replace "draw,fill" with "fill" in the exported tikz code to make the compiled image look like svg.

**Comment by ldevillez** [comment]
Yeah it is also possible to do that. But I think GeoGebra can directly export to tikz code so it could be an alternative way to do that :)
