### ISSUE TITLE
convert_svg is not importable from the module svg2tikz

### ISSUE THREAD

**Issue by bentriom** [xyz2tex/svg2tikz#124]
Hello again,

After I managed to install the package with pip, I had difficulties in using the `convert_svg` method. Indeed, I received the following error after executing `from svg2tikz import convert_svg`:
`ImportError: cannot import name 'convert_svg' from 'svg2tikz' (/opt/miniforge3/lib/python3.10/site-packages/svg2tikz/__init__.py)`

I read some of the package's code and I found a way of importing the function: `from svg2tikz.extensions.tikz_export import convert_svg`. But I don't think this is the desired behavior (according to the doc).

Thanks!

**Comment by ldevillez** [comment]
Hello again !

Yes it is not the intended behaviour, the next big milestones to reorder the package (without breaking anything) and this issues should be addressed :)

**Comment by ldevillez** [comment]
Hello @bentriom,
With the last version of the code (not released on pypi yet) you can directly import convert_file (for file and stream) or `convert_svg (str) directly from svg2tikz
