### ISSUE TITLE
Can't find attribute Switch.is_visible

### ISSUE THREAD

**Issue by ysalmon** [xyz2tex/svg2tikz#145]
**Describe the bug**
``Can't find attribute Switch.is_visible`` happens when trying to convert the attached file.

**Setup:**
 - Mode: python package
 - SVG2TikZ version: today's master
 - OS version: KUbuntu 22.04

**To Reproduce**
Have ![alternative](https://github.com/xyz2tex/svg2tikz/assets/536850/0d25626a-2b76-494d-94fd-e54c2575f7e8).

Do ``svg2tikz.convert_file("alternative.svg", t="raw")``

**Expected behavior**
At this point I am not sure.

**Additional context**
The exception is raised in inkex, and that is called by ``if style.get("display") == "none" or not node.is_visible:`` on line 781 in tikz_export.

**Comment by ysalmon** [comment]
Wrapping the offending line in a ``try`` / ``except AttributeError: pass`` (assuming objects that do not have a display attribute are to be shown) seems to work.

**Comment by ldevillez** [comment]
Hello,
Thanks for the heads up :)
