### ISSUE TITLE
Ignores all text

### ISSUE THREAD

**Issue by ysalmon** [xyz2tex/svg2tikz#146]
**Describe the bug**
Conversion ignores all texts in the SVG.

**Setup:**
 - Mode: python package
 - SVG2TikZ version: today's master
 - OS version: KUbuntu 22.04

**To Reproduce**
get SVG file ![alternative](https://github.com/xyz2tex/svg2tikz/assets/536850/08aa1f83-5d2a-461a-9287-29a88818027e)

do ``with open("/tmp/essai.tex", "w") as f : f.write(svg2tikz.convert_file("/tmp/alternative.svg", crop=True, t="raw"))``

**Expected behavior**
Generated TikZ code should contain ``\node``s for texts.

**Comment by ldevillez** [comment]
Thanks @ysalmon,
I will look into when I can :)
