### ISSUE TITLE
Text is filled with background color

### ISSUE THREAD

**Issue by ldevillez** [xyz2tex/svg2tikz#152]
**Describe the bug**
The fill color of a text is the color of the text for a svg.
The fill color of a node is the background color of the text for tikz code

**To Reproduce**
- Export a svg with text which has proprerty `fill`

**Comment by ysalmon** [comment]
In Inkscape, the background color setting for a text object sets the color of the text, so that should be translated to ``\node[text=...]`` instead of ``\node[fill=...]`` for text objects.
