### ISSUE TITLE
polylines & polygons reference unknown attribute 'get_points'

### ISSUE THREAD

**Issue by ratmice** [xyz2tex/svg2tikz#163]
**Describe the bug**
I started accidentally running svg2tikz on the rust-logo.svg file generated by `cargo doc`.
(i.e. when running find in my project directory without maxdepth), 

It looks like any svg with a `polygon` or `polyline` will produce an error `no attribute get_points`.

**Setup:**
 - Mode: inkscape/python package/shell tool
shell tool
 - SVG2TikZ version: [e.g. 1.2 or commit]
 bad5631
 - OS version: [e.g. Windows 11/macOS 12.6.3/Debian 11]
 - Inkscape version: [e.g. 1.1] when using with inkscape

**To Reproduce**
 - Input SVG
```
curl https://doc.rust-lang.org/static.files/rust-logo-151179464ae7ed46.svg >rust-logo
svg2tikz --figonly rust-logo.svg
```

 - Output result
```
AttributeError: 'Path' object has no attribute 'get_points'. Did you mean: 'end_points'?
```
 - Options

**Expected behavior**

**Additional context**

**Comment by ldevillez** [comment]
Thanks for the bug @ratmice :)
The svg2tikz should run now but unfortunately masking are not yet implemented and thus the logo cannot be correctly generated for now (but an issue is open)
