### ISSUE TITLE
Misplacement of element

### ISSUE THREAD

**Issue by drexhage** [xyz2tex/svg2tikz#174]
**Describe the bug (+ To Reproduce)**

 I'm still wondering about this input SVG: https://vega.github.io/editor/#/examples/vega-lite/stacked_bar_h (Go on export -> svg) but I don't know what the bug is. I would be glad if someone has enough insights to point me into the right direction here.

This is how inkscape displays it:

![image](https://github.com/xyz2tex/svg2tikz/assets/115697959/71af40d1-690e-4d48-93e7-9a6e23d52325)

This is what svg2tikz produces: 

![image](https://github.com/xyz2tex/svg2tikz/assets/115697959/8cd920bf-b5b2-4f7c-a2d8-ab5068b77c1b)

**Setup:**
 - Mode: shell tool
 - SVG2TikZ version: f142e3ae53e8698fdff0695c9d5f9f9320b29ad3
 - OS version: Linux

**Expected behavior**
"Variety" is supposed to be placed according to svg specs.

**Additional context**
I fixed the fact that this same svg wasn't compiling in #168 and I made the y-axis labels align correctly in #170 however I'm not deep enough into the program to understand why this is malfunctioning. There isn't really that much going on in the svg of this example in regards to the "variety" text, I think it has something to do with the transform `transform="translate(-88.8076171875,100) rotate(-90) translate(0,-2)"` (for example two translate operations) but I couldn't isolate the issue.

**Comment by ldevillez** [comment]
Hello @drexhage,
I will look into it :wink: Most of tested svg were from inkscape so it is good to have another source of svg. In inkscape, in general it's a transformation matrix and not multiple transformations on the same element.

**Comment by ldevillez** [comment]
Ok I found the problem but I need to find the right solution: the problem is the rotation from the transformation matrix. The origin from Inkscape and tikz is not the same by default (to avoid multiplying every tikz coordinate by -1. Normally you could have working figure with the option `--noreversey` but all the text is translated (the problem is propably linked).

**Comment by ldevillez** [comment]
I'm making some progress (you can check https://github.com/xyz2tex/svg2tikz/tree/174-misplacement-of-element with the option `--noreversey`) but I still have a small shift to correct

**Comment by ldevillez** [comment]
@drexhage can you test to see if everything is okay for you in #176 ? (the base document has wide margin so you maybe need to reduce them with the `geometry`package)
