### ISSUE TITLE
`svg2tikz/tikz_export.py` has invalid shabeng ending with `/`.

### ISSUE THREAD

**Issue by dreirund** [xyz2tex/svg2tikz#183]
The shabeng line of the file [`svg2tikz/tikz_export.py`](https://github.com/xyz2tex/svg2tikz/blob/master/svg2tikz/tikz_export.py#L1) ends with `/`, which is incorrect:

`head -n1 svg2tikz/tikz_export.py`:  
```
#!/usr/bin/env python/
```

The trailing `/` needs to be removed.

See also [&nearr;&hairsp;this `namcap` issue](https://gitlab.archlinux.org/pacman/namcap/-/issues/64#note_156153).

Regards!

**Comment by ldevillez** [comment]
Hello @dreirund,

Thanks for the head up:)
