### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by drazafin** [xyz2tex/svg2tikz#189]
I tried to install svg2tikz via " pip install svg2tikz " on MacOs 12.4 and got the following messages

Collecting svg2tikz
  Using cached svg2tikz-3.0.1-py3-none-any.whl (18 kB)
Collecting inkex<2.0.0,>=1.2.2
  Using cached inkex-1.3.0-py3-none-any.whl (196 kB)
Collecting lxml<5.0.0,>=4.9.2
  Using cached lxml-4.9.4-cp310-cp310-macosx_10_9_x86_64.whl
Collecting cssselect<2.0.0,>=1.1.0
  Using cached cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Collecting pySerial<4.0,>=3.4
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Requirement already satisfied: pyparsing>=3.0.9 in /usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages (from inkex<2.0.0,>=1.2.2->svg2tikz) (3.1.0)
Requirement already satisfied: packaging>=20.3 in /usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages (from inkex<2.0.0,>=1.2.2->svg2tikz) (23.0)
Collecting scour<0.38,>=0.37
  Using cached scour-0.37-py3-none-any.whl
Collecting PyGObject>=3.36
  Using cached PyGObject-3.46.0.tar.gz (723 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy<2.0.0,>=1.21.2 in /usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages (from inkex<2.0.0,>=1.2.2->svg2tikz) (1.25.0)
Requirement already satisfied: Pillow>=7.0.0 in /usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages (from inkex<2.0.0,>=1.2.2->svg2tikz) (10.0.1)
Collecting pycairo>=1.16.0
  Using cached pycairo-1.26.0-cp310-cp310-macosx_10_9_x86_64.whl
Requirement already satisfied: six>=1.9.0 in /usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages (from scour<0.38,>=0.37->inkex<2.0.0,>=1.2.2->svg2tikz) (1.16.0)
Building wheels for collected packages: PyGObject
  Building wheel for PyGObject (pyproject.toml): started
  Building wheel for PyGObject (pyproject.toml): finished with status 'error'
Failed to build PyGObject
  error: subprocess-exited-with-error

  × Building wheel for PyGObject (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-310
      creating build/lib.macosx-10.9-x86_64-cpython-310/pygtkcompat
      copying pygtkcompat/pygtkcompat.py -> build/lib.macosx-10.9-x86_64-cpython-310/pygtkcompat
      copying pygtkcompat/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pygtkcompat
      copying pygtkcompat/generictreemodel.py -> build/lib.macosx-10.9-x86_64-cpython-310/pygtkcompat
      creating build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_signalhelper.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_constants.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/pygtkcompat.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_ossighelper.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/importer.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_error.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_gtktemplate.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_propertyhelper.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/types.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/docstring.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/_option.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      copying gi/module.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi
      creating build/lib.macosx-10.9-x86_64-cpython-310/gi/repository
      copying gi/repository/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/repository
      creating build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/GIMarshallingTests.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/Gdk.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/Pango.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/GdkPixbuf.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/Gtk.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/GLib.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/GObject.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/Gio.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      copying gi/overrides/keysyms.py -> build/lib.macosx-10.9-x86_64-cpython-310/gi/overrides
      running build_ext
      Package gobject-introspection-1.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gobject-introspection-1.0' found
      Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.64.0')' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyGObject
ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects

**Comment by ldevillez** [comment]
Hello @drazafin, from the error stack i think PyGObject needs the development version (I will probably need to see why it is needed): To fix your error you can try thus to install PyGObject directly (something like `brew install pygobject3 gtk+3`)
