### ISSUE TITLE
`make -C docs/_build/latex all` fails with `! LaTeX Error: Unknown graphics extension: .svg.`.

### ISSUE THREAD

**Issue by dreirund** [xyz2tex/svg2tikz#199]
## Describe the bug

After generating LaTeX source from the documentation, building it fails with `! LaTeX Error: Unknown graphics extension: .svg.`.

## Setup:

 - Mode: Git clone from this repository
 - SVG2TikZ version: `git describe`: `v3.1.0-1-gc14dcde` (Commit ID c14dcde)
 - OS version: Artix GNU/Linux (rolling release)
 - Inkscape version: 1.3.2

## To Reproduce

1. `git clone https://github.com/xyz2tex/svg2tikz.git`
2. `cd svg2tikz`
3. `make -C docs latex`
4. `make -C docs/_build/latex all`
5. Observe issue:
   ```
   [...]
   [1] [2] [1] [2]
   Chapter 1.
   (/usr/share/texmf-dist/tex/latex/tex-gyre/ts1qtm.fd)
   (/usr/share/texmf-dist/tex/latex/txfonts/t1txtt.fd)
   Underfull \hbox (badness 10000) in paragraph at lines 175--177
   \T1/txtt/m/n/10 /Applications/Inkscape.app/Contents/Resources/extensions \T1/qt
   m/m/it/10 or \T1/txtt/m/n/10 ~/.config/inkscape/
   [3{/usr/share/texmf-dist/fonts/enc/dvips/tex-gyre/q-ts1.enc}]
   
   LaTeX Warning: Hyper reference `moduleguide:module-guide' on page 4 undefined o
   n input line 243.
   
   
   ! LaTeX Error: Unknown graphics extension: .svg.
   
   See the LaTeX manual or LaTeX Companion for explanation.
   Type  H <return>  for immediate help.
   ...                                              
                                                     
   l.259 ...inxincludegraphics{{articulated_leg}.svg}
                                                     
   ? 
   ```

## Expected behaviour

get PDF/PS/DVI file

## Additional context

Also happens with

* `make -C docs/_build/latex all-dvi`,
* `make -C docs/_build/latex all-ps`,
* `make -C docs/_build/latex all-pdf`.

**Comment by ldevillez** [comment]
Hello @dreirund 
Thanks for the bug report :)
Do you want to check the branch before the merge ?

**Comment by dreirund** [comment]
> *Do you want to check the branch before the merge ?*

I do not know github or more "advanced" git features.

How do I checkout that branch, that I just find as [pull/201](https://github.com/xyz2tex/svg2tikz/pull/201) here on github?

I might manually [download it as patch](https://github.com/xyz2tex/svg2tikz/pull/201.patch) and apply, though.

Regards!

**Comment by ldevillez** [comment]
The complete name of the branch is `199-make-c-docs_buildlatex-all-fails-with-latex-error-unknown-graphics-extension-svg` so if you can fetch the git, you should be able to test it. 

Or you could also download the whole project from the branch [here](https://github.com/xyz2tex/svg2tikz/tree/199-make-c-docs_buildlatex-all-fails-with-latex-error-unknown-graphics-extension-svg).

**Comment by dreirund** [comment]
> *Do you want to check the branch before the merge ?*

```
make -C docs latex
make -C docs/_build/latex all-pdf
```

now works for me.

**Comment by ldevillez** [comment]
Thanks :)
