### ISSUE TITLE
Something went totally wrong with curves in logo

### ISSUE THREAD

**Issue by sorsted** [xyz2tex/svg2tikz#210]
**Describe the bug**
I tried using `svg2tikz` on the logo of [DynamicWeb](https://dynamicweb.dk/). For copyright reasons, I shall not include the SVG source here, but you can easily obtain it from the source code of the website. Here is how the original looks in my browser:

![image](https://github.com/user-attachments/assets/c14e1b19-8475-4759-8950-2f1f91305244)

Here is how it looks after the conversion to TikZ:

![image](https://github.com/user-attachments/assets/c103d88e-51f6-473a-837a-c22b7405fa8b)

**Setup:**
 - Mode: command line
 - SVG2TikZ version: 3.1.10
 - OS version: Windows 11

**Comment by ldevillez** [comment]
Hello @sorsted,

Thanks for the feedback, I will try to look at it soon :)

**Comment by ldevillez** [comment]
Should be fixed in the PR #211 :

With the code of the branch
![screenshot_20240924_190543](https://github.com/user-attachments/assets/4025b257-04a8-4b21-aa06-180b2831c51d)

Merging and publishing a new release :)
