### ISSUE TITLE
Export svg from Inkscape to Tikz leaves out axis descriptions

### ISSUE THREAD

**Issue by stoettner** [xyz2tex/svg2tikz#29]
Hi Kjell,
first of all thanks for the great Inkscape exporter. I use it very often to export a svg graphic from Inkscape for use in LaTex beamer. It greatly facilitates to speed up LaTex beamer presentations and helps humongously in cutting down on the Tikz learning curve.

One thing I saw is when exporting a svg graph something like a scatter plot the Tikz misses out on the x and y axis descriptions. Refer to the svg and Tikz export code [here](https://www.dropbox.com/sh/x8j6nl73d4dwsix/AACALLYVOILPyEtP7XEthVWua?dl=0).

Is there a way to include the this also?

Many thanks and keep up that great work.
wolf

**Comment by ldevillez** [comment]
Hello @stoettner
Sorry for the late reply, do you still experience this bug ?

**Comment by ldevillez** [comment]
It should be fix by #82
