### ISSUE TITLE
Detecting round corners from the svg and applied it to tikz

### ISSUE THREAD

**Issue by matsalleh92** [xyz2tex/svg2tikz#33]
In inkscape:
![image](https://cloud.githubusercontent.com/assets/12034228/21056627/480b9182-be2e-11e6-8a1b-17bfd1d8c0c6.png)
In Tickz:
![image](https://cloud.githubusercontent.com/assets/12034228/21056634/511e3388-be2e-11e6-9ee6-dbb9eca28f05.png)

**Comment by Hans-MartinHannibalLauridsen** [comment]
This would be a nice feature.

**Comment by ldevillez** [comment]
It should be fully implemented now and fixed by #116
