### ISSUE TITLE
Odd Positioning

### ISSUE THREAD

**Issue by Aikhjarto** [xyz2tex/svg2tikz#34]
Graphic elements are wrongly positioned.
I made a very simple test file file with paths elements, a text a rectangle and an ellipse. 
Here is the file:
[Zeichnung.zip](https://github.com/kjellmf/svg2tikz/files/970976/Zeichnung.zip)

Here is a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/3519989/25625937/334f7cb2-2f5e-11e7-9bea-27c19407a921.png)

After producing a standalone tikz figure with svg2tikz and reendering it with pdflatex, the individual elements are wrongly scaled and placed:
![zeichnung](https://cloud.githubusercontent.com/assets/3519989/25625986/5ac8639e-2f5e-11e7-8c2d-f7ab6390a6fd.png)

**Comment by thisirs** [comment]
Same problem here. This seems to be a "user unit" problem. Looking at the code, shapes (rectangle, circle,...) are treated separately from paths (spirals, spline, ...). Shapes' dimension go through unittouu but paths's are not. You need to change your user unit to "px" (this worked for me) in File > Documents Properties and have 1 user units per px

HTH

**Comment by baedsch** [comment]
Thanks @thisirs , this also works for Text fields

**Comment by ldevillez** [comment]
Is fixed by #73
