### ISSUE TITLE
Make svg2tikz compatible with Inkscape 1.0

### ISSUE THREAD

**Issue by yurytch** [xyz2tex/svg2tikz#42]
(I know the project is unmaintained, yes. Maybe someone would offer some advice on the issue.)
So, this extension won't work in Inkscape 1.0* packaged as AppImage. It tries to import simplepath and simplestyle but those aren't in package 'extensions' dir, but in 'extensions/inkex/deprecated-simple' instead. I tried 'groping around', adding 
`sys.path.append( module.__path__ + '/extensions/inkex/deprecated-simple' )` 
before the importing part, but to no good result. And I do not know neither python nor inkscape extensions subsystem well enough.

**Comment by aalavandhaann** [comment]
Dear @yurytch ,

Do not worry. Just let us know what do you mean by **AppImage of Inkscape 1.0***. Do you mean a standalone version of Inkscape downloaded for Mac? Can you give more details? So we try to solve this once for all. 

Regards,
#0K

**Comment by yurytch** [comment]
Thank you for looking into it! 
I'm using the 64-bit Linux AppImage which is available from inkscape.org on 'Download'->'Upcoming Version (1.0)' path.

**Comment by kjellmf** [comment]
Changed the title. 
Some changes in version 1:
https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#For_extension_writers
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0

**Comment by aalavandhaann** [comment]
Hey @kjellmf ,
Great you have identified the issue. So what do we do now? We do the changes as proposed in the URL and we lose compatibility with versions < 1.0, if we don't do it then we lose comptability with versions >= 1.0, So create a separate branch for this? To support versions > 1.0?

Regards,
#0K

**Comment by yurytch** [comment]
Well, at least I have now sort of a manual how to (try to) make it work in my case. Thanks!

**Comment by jospic** [comment]
Hi, I partially converted the extension for version 1.0 of Inkscape, but there is still something that I can't solve... 
Any suggestions? 
Thanks.
-j

Please try this version:
[svg2tikz.zip](https://github.com/kjellmf/svg2tikz/files/4102050/svg2tikz.zip)

**Comment by aalavandhaann** [comment]
Hi @jospic ,

What is the problem you are facing? 

Regards,
#0K

**Comment by jospic** [comment]
> Hi @jospic ,
> 
> What is the problem you are facing?
> 
> Regards,
> #0K

This is script errors:

**Traceback (most recent call last):
  File "tikz_export.py", line 1476, in <module>
    main_inkscape()
  File "tikz_export.py", line 1459, in main_inkscape
    effect = TikZPathExporter(inkscape_mode=True)
  File "tikz_export.py", line 629, in __init__
    self._set_up_options()
  File "tikz_export.py", line 668, in _set_up_options
    parser.add_argument('-o', '--output',  type=str,
  File "C:\Program Files (x86)\inkscape\lib\python3.8\argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "C:\Program Files (x86)\inkscape\lib\python3.8\argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "C:\Program Files (x86)\inkscape\lib\python3.8\argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Program Files (x86)\inkscape\lib\python3.8\argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "C:\Program Files (x86)\inkscape\lib\python3.8\argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Program Files (x86)\inkscape\lib\python3.8\argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -o/--output: conflicting option string: --output**

**Comment by geodavic** [comment]
What is the state of this extension with Inkscape 1.0? I just tried cloning master into the extensions folder, but when I restarted and tried to export an svg selection, the "Export to Tikz Path..." option was not clickable. Is this a known issue?

**Comment by aalavandhaann** [comment]
Dear Geomdavic,

I would advice you to use the export pdf functionality of Inkscape to
export image + text to Latex.

**Comment by geodavic** [comment]
Thank you for the suggestion. I actually need tikz rather than a pdf export.

I got the same error that @jospic got and tried a fix by removing `'--output'` from line 668. However, doing so relayed another error whose trace was:

`tikz_export.py:1460: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
Traceback (most recent call last):
  File "tikz_export.py", line 1476, in <module>
    main_inkscape()
  File "tikz_export.py", line 1460, in main_inkscape
    effect.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated.py", line 180, in affect
    return self.run(args=args)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "tikz_export.py", line 1350, in effect
    nodes = self.selected_sorted
AttributeError: 'TikZPathExporter' object has no attribute 'selected_sorted'`

Are there any other people having this issue? I really like this extension and would hate to not be able to use it.

**Comment by geodavic** [comment]
> What is the state of this extension with Inkscape 1.0? I just tried cloning master into the extensions folder, but when I restarted and tried to export an svg selection, the "Export to Tikz Path..." option was not clickable. Is this a known issue?

For anyone else that ran into this, I fixed by placing the three scripts located in linked in the zip file above directly into the extensions folder for inkscape. This made the "Export to TIkZ Path ... " button clickable (but, as my previous post says, there are errors still).

**Comment by aalavandhaann** [comment]
i believe you need the TIKZ for latex purposes right? It does exactly that

**Comment by geodavic** [comment]
What I need is the raw TikZ code to put into my LaTeX document. Does what you're suggesting do that? I don't want a pdf of the SVG; I want the TikZ code so that I can compile it into a pdf which has other things in it as well.

**Comment by aalavandhaann** [comment]
Yes it does that. In the PDF export you see that option of exporting
drawings as PDF and the text with latex. I will try to give an example as
soon as I am in front of my computer

**Comment by geodavic** [comment]
I just tried what you said, and I see what you mean. However, it is still not what I want unfortunately. What that does is it generates a TeX file which just references the pdf that I exported from Inkscape. Like the following:

 \put(0,0){\includegraphics[width=\unitlength,page=1]{drawing.pdf}}%

Where drawing.pdf is the exported pdf of my drawing. I want to be able to have the actual TikZ code that makes the drawing (so I can maybe change the drawing and add to it). That's what this extension used to do for me before it stopped working in the new Inkscape :(  

Thank you for your help anyway!

**Comment by epichub** [comment]
I got this plugin to work on MacOS with inkscape 1.0.1. Still get some warnings, but it works, both to file and clipboard.
The following patch is based on the zip file posted in this issue thread by @jospic .
`diff -u a/tikz_export.py b/tikz_export.py
--- a/tikz_export.py	2020-01-23 09:40:06.000000000 +0100
+++ b/tikz_export.py	2020-11-23 11:57:12.000000000 +0100
@@ -640,6 +640,7 @@
         self.gradient_code = ""
         self.output_code = ""
         self.used_gradients = set()
+        self.selected_sorted = []
 
     def _set_up_options(self):
         parser = self.arg_parser
@@ -665,7 +666,7 @@
                              dest="wrap",
                              help="Wrap long lines")
         self._add_booloption(parser, '--indent', default=True)
-        parser.add_argument('-o', '--output',  type=str,
+        parser.add_argument('-to', '--tikzoutput',  type=str,
                           dest='outputfile', default=None,
                           help="") 
 
@@ -1400,7 +1401,7 @@
                 f.write(self.output_code)
                 f.close()
                 # Serialize document into XML on stdout
-            self.document.write(sys.stdout)
+            self.document.write(sys.stdout.buffer)
 
         if self.options.mode == 'output':
             print(self.output_code.encode('utf8'))
diff -u a/tikz_export_effect.inx b/tikz_export_effect.inx
--- a/tikz_export_effect.inx	2020-01-23 09:40:06.000000000 +0100
+++ b/tikz_export_effect.inx	2020-11-23 11:53:01.000000000 +0100
@@ -19,7 +19,7 @@
             <param name="clipboard" type="boolean" _gui-text="Export to clipboard">false</param>
             <param name="wrap" type="boolean" _gui-text="Wrap paths">true</param>
             <param name="indent" type="boolean" _gui-text="Indent groups">true</param>
-            <param name="output" type="string" _gui-text="Output filename">none</param>
+            <param name="tikzoutput" type="string" _gui-text="Output filename">none</param>
             
             <param name="latexpathtype" type="boolean" _gui-text="Path comply for tikz mode">false</param>
             <param name="removeabsolute" type="string" _gui-text="Remove from path"></param>
`

**Comment by geodavic** [comment]
@epichub Thank you so much! I don't seem to have the same version of `tikz_export.py` that you do, since I can't locate the same lines to change. Is that difference call relative to master?

**Comment by JuanGa271** [comment]
Cordial saludo, hay alguna solución para Windows 10, y la versión de inkspace 1.0.1 ???

**Comment by kjellmf** [comment]
Fixed in 8e56b57
