### ISSUE TITLE
update to 96 DPI

### ISSUE THREAD

**Issue by johnyf** [xyz2tex/svg2tikz#52]
As of 91236b5b2eb1449206bb31dcdd83525db65eec30, 90 DPI are used for the unit conversion, but `inkscape >= 0.91` has changed to 96 DPI (pixels per inch, user units per inch): https://wiki.inkscape.org/wiki/index.php/Units_In_Inkscape

https://github.com/kjellmf/svg2tikz/blob/91236b5b2eb1449206bb31dcdd83525db65eec30/svg2tikz/inkexlib/inkex.py#L41-L42

**Comment by ldevillez** [comment]
Fixed by #68 
Thanks :)
