### ISSUE TITLE
It doesn't work for me :(

### ISSUE THREAD

**Issue by farshadrasuli** [xyz2tex/svg2tikz#54]
Help to handle this error.
>OS: windows 7
>Inkspace version: 1.0.1

tikz_export.py:645: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  parser = self.OptionParser
Traceback (most recent call last):
  File "tikz_export.py", line 1478, in <module>
    main_inkscape()
  File "tikz_export.py", line 1461, in main_inkscape
    effect = TikZPathExporter(inkscape_mode=True)
  File "tikz_export.py", line 629, in __init__
    self._set_up_options()
  File "tikz_export.py", line 646, in _set_up_options
    parser.set_defaults(codeoutput='standalone', crop=False, clipboard=False,
AttributeError: 'TikZPathExporter' object has no attribute 'set_defaults'

**Comment by Iam5B** [comment]
Use inkspace 0.92.4. The extension is updated 13 months ago(2020-1), and 0.92.4 is a version released before 0.92.5(2020-4). @farshadrasuli

**Comment by kjellmf** [comment]
Fixed in 8e56b57
