### ISSUE TITLE
[bug] the convert result varys from the origin svg

### ISSUE THREAD

**Issue by Freed-Wu** [xyz2tex/svg2tikz#55]
Reproduce Procedure
-------------------

```{.sh}
pdf2svg ustc_background_1.pdf ustc_background_1.svg
```

Use svg2tikz to convert original svg to a standalone tex `main.tex`.

then 

```{.sh}
sed -i '2s/article/standalone/' main.tex
latexmk -pvc- main.tex
```

Origin
------
[ustc_background_1.pdf](https://github.com/kjellmf/svg2tikz/files/5495401/ustc_background_1.pdf)
![ustc_background_1](https://user-images.githubusercontent.com/32936898/98263464-d5243080-1fc1-11eb-9053-df94b2b9f77b.png)

Result
------
[main.pdf](https://github.com/kjellmf/svg2tikz/files/5495404/main.pdf)
![main](https://user-images.githubusercontent.com/32936898/98263479-d9e8e480-1fc1-11eb-8661-449ccf4a4048.png)

the blue strip of the origin pdf disappeared. and a white strip occurred on
the left side of the result.

**Comment by ldevillez** [comment]
The problem is that Linear gradient are not yet implemented (see #1 )
