### ISSUE TITLE
Installation documentation seems to be missing

### ISSUE THREAD

**Issue by phlummox** [xyz2tex/svg2tikz#56]
Hi, I note that the installation documentation has an empty section on
["Manual installation from a mercurial checkout"][hg-checkout]. I am guessing this should now be "... a Git checkout", and should look something [like this][patch].

I'm happy to make a pull request if you'd like this information added.

(Also, as a by-the-by -- I saw there's an issue filed for creating a "readthedocs" version of the documentation. I'm afraid I have never done that - but I think it'd be pretty straightforward to modify the current .travis build so that the documentation is converted to GitHub-flavoured markdown and added as, say, a wiki page here. Happy to look into that if you'd like.)

(And as another by-the-by, I notice the .travis build [is failing][travis] - it looks as if by default, pip is trying to install a version of lxml which is no longer compatible with the version of Python available on Ubuntu xenial. I can check and see if there's a quick fix for that.)

[hg-checkout]: https://github.com/xyz2tex/svg2tikz/blob/91236b5b2eb1449206bb31dcdd83525db65eec30/docs/install.rst#manual-installation-from-a-mercurial-checkout

[patch]: https://github.com/phlummox-patches/svg2tikz/blob/29782cc972fdce0d5e7327598c76620cc7b975bf/docs/install.rst#manual-installation-from-a-git-checkout

[travis]: https://travis-ci.com/github/phlummox-patches/svg2tikz/jobs/469809154

**Comment by kjellmf** [comment]
Hi. I have not worked on this project for a very long time, so there are unfortunately a lot of things that are missing and outdated. Feel free to submit a pull request. 

Regarding readthedocs. The (incomplete) documentation is already in a format that can be used by readthedocs. Whats missing is creating a project for it on the readthedocs site.

**Comment by phlummox** [comment]
Hi, thanks for the reply! No worries, I'll submit a PR for the "Mercurial checkout" stuff. And will let you know if I spot any quick fixes for the Travis build.
