### ISSUE TITLE
Phython problems with tikz export from inkscape - no export obtained

### ISSUE THREAD

**Issue by scfrank-pri** [xyz2tex/svg2tikz#58]
tikz_export.py:645: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  parser = self.OptionParser
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "tikz_export.py", line 1478, in <module>
    main_inkscape()
  File "tikz_export.py", line 1461, in main_inkscape
    effect = TikZPathExporter(inkscape_mode=True)
  File "tikz_export.py", line 629, in __init__
    self._set_up_options()
  File "tikz_export.py", line 646, in _set_up_options
    parser.set_defaults(codeoutput='standalone', crop=False, clipboard=False,
AttributeError: 'TikZPathExporter' object has no attribute 'set_defaults'

**Comment by kjellmf** [comment]
Fixed in 8e56b57
