### ISSUE TITLE
Tips to make doc, package, etc.

### ISSUE THREAD

**Issue by FabriceSalvaire** [xyz2tex/svg2tikz#59]
**This project can be useful to draft with Inkscape and polish with Tikz...**

I have several Python libraries where someone can pick up code
* invoke tasks to make doc, wheel, upload on PyPI etc.
* to upgrade the setup.py to setup.cfg etc.
* to generate "executable" see setup.cfg
* to generate doc with Sphinx
* to upload gh page

I often copy-paste this from project to project.

You can look at
* https://github.com/FabriceSalvaire/PySpice

And I have SVG,TeX, geometry, display code in
* https://github.com/FabriceSalvaire/Patro/tree/master/Patro/FileFormat/Svg
* https://github.com/FabriceSalvaire/Patro/tree/master/Patro/GraphicEngine/TeX
* https://github.com/FabriceSalvaire/Patro/blob/master/examples/file-format/svg/svg-import.py
* https://github.com/FabriceSalvaire/Musica/tree/master/Musica/Tex

**But I don't have much time....** but you can ping me for questions

**Comment by ldevillez** [comment]
Thanks ! Everything should be good now 👍
