### ISSUE TITLE
Enhancement: recover shape (like rectangle) from path

### ISSUE THREAD

**Issue by FabriceSalvaire** [xyz2tex/svg2tikz#60]
I made a try to import a PDF generated by [xournalpp](https://github.com/xournalpp/xournalpp) in Inkscape.  Rectangles are lost, but we can match the coordinates to guess it is a shape.

**Comment by ldevillez** [comment]
Hi @FabriceSalvaire, from what I understand it is more linked to Inkscape or xournalpp
