### ISSUE TITLE
Compatibility with Cairo generated SVGs

### ISSUE THREAD

**Issue by EvoArt** [xyz2tex/svg2tikz#63]
Hi there

Thanks for this great package! Latex integration is such an important feature.

I've recently used svg2tikz to convert SVGs produced by [CairoMakie.jl](https://makie.juliaplots.org/stable/)  to Tikz code. Unfortunately, none of the text (axis ticks) show up. But there are empty nodes who's positions correspond to the positions of the individual letters/digits in may CairoMakie plots. I was just wondering if svg2tikz is known to be able to parse text from Cairo generated SVGs or not?

**Comment by kjellmf** [comment]
Hi. First time I've heard about CairoMakie.jl so I don't know.  Could it be that CairoMakie.jl outputs text as paths instead of text elements?

**Comment by ldevillez** [comment]
Hello @EvoArt, do you have any minimal example where SVG2Tikz is not working ? :)

**Comment by ldevillez** [comment]
Hey @EvoArt,
This should be good now (I mean for a first and naive implementation):
![screenshot_20230209_165350](https://user-images.githubusercontent.com/15208526/217865924-ac94fa14-3229-4add-8b45-772039cd6714.png)

It's updated on the repo but not yet on Pypi :)

**Comment by EvoArt** [comment]
That's amazing! Thank you so much.
