### ISSUE TITLE
svg2tikz: "\Inkscape\bin\pythonw.exe: can't find '__main__' module"

### ISSUE THREAD

**Issue by pietrocaradonna** [xyz2tex/svg2tikz#66]
Hi,
I am hoping someone can help me. I am having problems exporting a svg picture to a tikz picture using Inkscape. I keep getting the following error message

"C:\Program Files (x86)\Inkscape\bin\pythonw.exe: can't find '__main__' module in 'C:\\Program Files (x86)\\Inkscape\\bin'"

I downloaded and installed [Inkscape-1.2.1](https://inkscape.org/release/inkscape-1.2.1/windows/32-bit/msi/dl/) for Windows 10 and downloaded [svg2tikz-master folder](https://github.com/paaguti/svg2tikz) and copied and pasted __init__.py, tikz_export.py, tikz_export_effect.inx and tikz_export_output.inx into the C:\Program Files (x86)\Inkscape\share\inkscape\extensions directory.

I then open Inkscape and load my image and go to Extensions->Export->Export to TikZ path.. as shown in the following screen shot
![1](https://user-images.githubusercontent.com/57653088/198745516-03259cae-ed70-4886-b01d-4870470f5fa4.png)
(I DO NOT KNOW WHY THERE ARE MULTIPLE INSTANCES OF "Export to TikZ path..")

I choose the first option of  "Export to TikZ path.." and fill in the popup windows as shown in the next screen shot
![3](https://user-images.githubusercontent.com/57653088/198745584-fec15f44-bc0d-4ead-90f2-9e63ce8d89e7.png)

I then press on "Apply" and get the following message
![4](https://user-images.githubusercontent.com/57653088/198745610-214d4e61-6887-4d92-b416-5169af011629.png)

Does someone know how to fix this error?

Thank you

**Comment by ldevillez** [comment]
Hello @pietrocaradonna,
Could you check with the last version of the code ? :)

**Comment by moshpirit** [comment]
Same happens with me. I've just downloaded the code and move it to `~/.config/inkscape/extensions/`. I'm trying to export it as tikz but I'm getting the `/usr/bin/python3: can't find '__main__' module in '/home/alberto/.'` error.

**Comment by ldevillez** [comment]
Hello @moshpirit, thanks for the bump.
Can you try to run the test ? Just go in the `tests` folder and run `python3 test_XXXX.py`.

Also as a sanity check, did you put the whole code in the folder `~/.config/inkscape/extensions/` or did you put only the `tikz_export_XXX` files ?

**Comment by 1587REST** [comment]
Hello, i have the same issue when i want to run my kukatools extension.... someone may help me please???
do i need a latest version of inkscape???
thanks, in advance

**Comment by ldevillez** [comment]
Hello @1587REST 
I did not advance on this issue as I did not have way to reproduce the problem. It could be a good idea to:
- List your system / inkscape / extensions version
- Look at the log of inkscape

**Comment by ldevillez** [comment]
Closing as not reproducable
