### ISSUE TITLE
Start/End markers of a path are not supported

### ISSUE THREAD

**Issue by kjellmf** [xyz2tex/svg2tikz#7]
I tried to export to TikZ my scheme which contains lots of arrows. Each arrow 
is a path with ArrowEnd terminating marker. All these paths are exported, but 
they contain no arrows.

Any workaround possible?

Markers are currently not supported. A workaround is to convert markers to paths in
the Path menu: Path -> Stroke to path

GC issue: https://code.google.com/p/inkscape2tikz/issues/detail?id=20

**Comment by ldevillez** [comment]
Closed by #83
