### ISSUE TITLE
Inkex dependency error

### ISSUE THREAD

**Issue by tch1001** [xyz2tex/svg2tikz#78]
I get the following error message from 
```
pip install .
```
Message:
```
ERROR: Could not find a version that satisfies the requirement inkex<2.0.0,>=1.2.2+dairiki.1 (from svg2tikz) (from versions: 1.0, 1.0.1)
```
I've checked that I have installed `inkex` version 1.0.1. Any help would be greatly appreciated! Thanks!

**Comment by tch1001** [comment]
I managed to bypass this by modifying the `pyproject.toml` to become
```
[tool.poetry.dependencies]
python = "^3.9"
lxml = "^4.9.2"
inkex = "^1.0.0"
```
But I'm not sure if this will break anything, just sharing that it worked for me!

**Comment by ldevillez** [comment]
Thanks @tch1001 
The inkex package from pypi is not updated with the current version of the builded inkex of inkscape so I'm not sure that you have the correct version of `inkex`.

I've updated the readme but you need to add an extra url repository to find the `inkex`package:
```
export PIP_EXTRA_INDEX_URL=https://gitlab.com/api/v4/projects/40060814/packages/pypi/simple
```
