### ISSUE TITLE
Switch to cm instead of pixels?

### ISSUE THREAD

**Issue by kjellmf** [xyz2tex/svg2tikz#9]
A request for enhancement:
the TikZ code produced by inkscape2tikz would be much easier to edit if instead of pixels it used cm (which is the default in tikz) as primary dimension, and if y-coordinate was multiplied by -1, so instead of 

```
\begin{tikzpicture}[y=0.80pt,x=0.80pt,yscale=-1]
\path[draw=black] (168.0839,258.1656)...
```

it would produce

```
\begin{tikzpicture}[y=1cm, x=1cm]
\path[draw=black] (4.706, -7.228)...
```

(or better yet, replace y by (height-y) to have values positive).

From the commented out code in function transform(self, coord_list, cmd=None) I see that this feature was probably planned (or at least considered). Or is there any reason why it was removed?

GC issue: https://code.google.com/p/inkscape2tikz/issues/detail?id=27

**Comment by joulev** [comment]
Any update on this one?
