### ISSUE TITLE
All paths are exported, not just selected ones

### ISSUE THREAD

**Issue by samcarter** [xyz2tex/svg2tikz#97]
First of all I'd like to thank you for working on this useful tool. I'm using it as a basis for all kinds of latex packages like https://github.com/samcarter/tikzlings

------

The help tab of the extension says:

> An Inkscape extension for exporting SVG paths as TikZ/PGF paths.
> The extension will export the selected paths. If no path is selected, all paths are exported.

If I remember correctly, this used to work with inkscape 0.92 and a previous version of svg2tikz. However it seems that with the current version all paths are exported, not just the selected paths.

For example in the document below, I selected one of the ellipses.

<img width="1326" alt="Screenshot 2023-04-05 at 14 46 13" src="https://user-images.githubusercontent.com/43832342/230084509-2b3394b9-f72e-4290-bdf1-a21163340599.png">

The resulting TikZ code contains both ellipses:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{tikz}

\begin{document}
\definecolor{cffffff}{RGB}{255,255,255}
\definecolor{c505658}{RGB}{80,86,88}

\def \globalscale {1.000000}
\begin{tikzpicture}[y=1cm, x=1cm, yscale=\globalscale,xscale=\globalscale, inner sep=0pt, outer sep=0pt]
\path[draw=cffffff,fill=c505658,opacity=0.450,line cap=round,line join=round,line width=0.198cm] (10.6341, 17.6186) ellipse (6.4961cm and 6.0512cm);

\path[draw=cffffff,fill=c505658,opacity=0.450,line cap=round,line join=round,line width=0.198cm] (12.1443, 24.9807) ellipse (11.4794cm and 3.2925cm);

\end{tikzpicture}
\end{document}
```

Is this a problem with inkscape or with svg2tikz?

----

I'm using 

- macOS 12.6.3
- Inkscape 1.2.2 (b0a84865, 2022-12-01)
- svg2tikz v1.2.0 (or more precisely this commit https://github.com/xyz2tex/svg2tikz/commit/695cca589566b6f8bc74381be8b349d737fc0482 )

**Comment by ldevillez** [comment]
Hello @samcarter
Thanks for the feedback :)

with Inkscape 1.0 there was a big update of the extension setup from Inkscape. I did not manage yet to test all the features (but it is WIP #92 ). In the testsuite there is a test for the select id of elements and it still works.
But I did not inspect this test (so maybe a fault there). Otherwise Inkscape may have updated their workflow form transmitting selected elements (which is more likely).

I will look in more details when I have time :)

**Comment by samcarter** [comment]
It seems to work fine when downgrading to Inkscape 1.1.2 (b8e25be8, 2022-02-05)

**Comment by ldevillez** [comment]
Thanks :)
I've started to investigate and I cannot get back the selected ids but i will search a bit more before opening an issue for inkscape.

**Comment by ldevillez** [comment]
Hello @samcarter 
Now it should be fixed on the master branch but only when you use SVG2TikZ from the extension menu and not from the save as menu.

Also the gui of the extension should have been updated so if you have any feedback feel free to open a new issues :)

**Comment by samcarter** [comment]
@ldevillez  Thanks a lot for the fix! I just tested and just exporting the selected paths now works perfectly! 

(I love that one can now define a scaling factor in the GUI. I used to change the scaling factor in the source of svg2tikz, so that I got the scaling I wanted. Really nice that there is now an easy to use option.)
