### ISSUE TITLE
Wrong y-coordinates if object is inside scope

### ISSUE THREAD

**Issue by AlbertoJimenezRuiz** [xyz2tex/svg2tikz#98]
First of all, thank you for creating this extension. It has been very useful for me.

**Bug description**

The extension returns tikz code which has wrong y-coordinates if the objects are inside a scope.

**My Setup**

- Inkscape 1.1
- Ubuntu 22.10
- svg2tikz [2023-04-10 version]

**How to reproduce**

For example, converting the following svg, which has a layer with a translation transformation,
![example](https://user-images.githubusercontent.com/50967855/230982361-c47eff86-0239-4de9-b34c-3997770a463b.svg)

produces tikz code that plots this figure:

![imagen](https://user-images.githubusercontent.com/50967855/230982641-0d68637c-811f-46e6-80ce-01ee4d4748ec.png)

As it can be seen, the horizontal coordinates are fine, but the y-coordinates are wrong.

**Possible cause**

Tikz and the SVG format uses opposite origins for the origin. (Top-left vs Bottom-left), thus the y-coordinate is flipped around. Svg2tikz performs this operation to fix it: new_y = drawing_height - old_y (function update_height). 
However, the y-coordinate is "fixed" at the beginning, and that messes the coordinates.

If there is a transformation (represented as a scope in tikz, this should be the last step). 
final_y = fix_y_coordinate(transformation2(transformation1(y)))

Instead, the transformation is performed at the first step:
buggy_final_y = transformation2(transformation1(fix_y_coordinate(y)))

**A workaround**

I found a workaround. 

1. Change the default value of noreversey to False, avoiding the y-coordinate flipping
2. Wrap the entire figure around a \begin{scope}[yscale=-1]  \end{scope} block.

It is not perfect, but it works for me.

**Comment by ldevillez** [comment]
Hello @AlbertoJimenezRuiz 
Thanks for your message :)
Yeah, noreversey was tested but not for all the cases. Now that I've finished updating all the test I can better track those issues.

I will look into this bug when I have time !

**Comment by ldevillez** [comment]
Hello @AlbertoJimenezRuiz 
Could you check with the code in #100 to see if it fixes your problems ?
You should be able to use the default options but --noreversey should also work out of the box without adding a yscale=-1

**Comment by AlbertoJimenezRuiz** [comment]
Hello, and thanks for all. I have checked that your fixes. The exporter now works fantastic. Now the drawings look perfect!

Thanks
